"""add order schema

Revision ID: 6fe0534d9aa2
Revises: 80fb72cf305c
Create Date: 2026-06-27 09:06:22.160488

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6fe0534d9aa2'
down_revision: Union[str, Sequence[str], None] = '80fb72cf305c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('orders',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('base_asset_id', sa.UUID(), nullable=False),
    sa.Column('quote_asset_id', sa.UUID(), nullable=False),
    sa.Column('idempotency_key', sa.String(length=128), nullable=True),
    sa.Column('reservation_transaction_id', sa.UUID(), nullable=False),
    sa.Column('side', sa.Enum('buy', 'sell', name='order_side'), nullable=False),
    sa.Column('status', sa.Enum('open', 'canceled', 'filled', name='order_status'), server_default='open', nullable=False),
    sa.Column('price', sa.Numeric(precision=38, scale=18), nullable=False),
    sa.Column('quantity', sa.Numeric(precision=38, scale=18), nullable=False),
    sa.Column('remaining_quantity', sa.Numeric(precision=38, scale=18), nullable=False),
    sa.Column('reserved_amount', sa.Numeric(precision=38, scale=18), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('base_asset_id <> quote_asset_id', name=op.f('ck_orders_different_assets')),
    sa.CheckConstraint('price > 0', name=op.f('ck_orders_price_positive')),
    sa.CheckConstraint('quantity > 0', name=op.f('ck_orders_quantity_positive')),
    sa.CheckConstraint('remaining_quantity >= 0 AND remaining_quantity <= quantity', name=op.f('ck_orders_remaining_quantity_range')),
    sa.CheckConstraint('reserved_amount > 0', name=op.f('ck_orders_reserved_amount_positive')),
    sa.ForeignKeyConstraint(['base_asset_id'], ['assets.id'], name=op.f('fk_orders_base_asset_id_assets'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['quote_asset_id'], ['assets.id'], name=op.f('fk_orders_quote_asset_id_assets'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['reservation_transaction_id'], ['ledger_transactions.id'], name=op.f('fk_orders_reservation_transaction_id_ledger_transactions'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_orders_user_id_users'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_orders')),
    sa.UniqueConstraint('reservation_transaction_id', name='reservation_transaction'),
    sa.UniqueConstraint('user_id', 'idempotency_key', name='user_idempotency_key')
    )
    op.create_index(op.f('ix_orders_base_asset_id'), 'orders', ['base_asset_id'], unique=False)
    op.create_index(op.f('ix_orders_quote_asset_id'), 'orders', ['quote_asset_id'], unique=False)
    op.create_index(op.f('ix_orders_user_id'), 'orders', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_orders_user_id'), table_name='orders')
    op.drop_index(op.f('ix_orders_quote_asset_id'), table_name='orders')
    op.drop_index(op.f('ix_orders_base_asset_id'), table_name='orders')
    op.drop_table('orders')
    op.execute("DROP TYPE IF EXISTS order_status")
    op.execute("DROP TYPE IF EXISTS order_side")
    # ### end Alembic commands ###
