"""add wallets and ledger tables

Revision ID: 80fb72cf305c
Revises: c82f192c627d
Create Date: 2026-06-27 08:08:34.721377

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '80fb72cf305c'
down_revision: Union[str, Sequence[str], None] = 'c82f192c627d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('assets',
    sa.Column('code', sa.String(length=16), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('precision', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('code = upper(code)', name=op.f('ck_assets_code_uppercase')),
    sa.CheckConstraint('precision >= 0 AND precision <= 18', name=op.f('ck_assets_precision_range')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_assets'))
    )
    op.create_index(op.f('ix_assets_code'), 'assets', ['code'], unique=True)
    op.create_table('ledger_transactions',
    sa.Column('reference', sa.String(length=64), nullable=False),
    sa.Column('idempotency_key', sa.String(length=128), nullable=True),
    sa.Column('transaction_type', sa.Enum('funding', 'order_reserve', 'order_release', 'trade', name='ledger_transaction_type'), nullable=False),
    sa.Column('status', sa.Enum('posted', 'reversed', name='ledger_transaction_status'), server_default='posted', nullable=False),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_ledger_transactions')),
    sa.UniqueConstraint('idempotency_key', name=op.f('uq_ledger_transactions_idempotency_key'))
    )
    op.create_index(op.f('ix_ledger_transactions_reference'), 'ledger_transactions', ['reference'], unique=True)
    op.create_table('wallets',
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('asset_id', sa.UUID(), nullable=False),
    sa.Column('owner_type', sa.Enum('user', 'system', name='wallet_owner_type'), nullable=False),
    sa.Column('system_account', sa.String(length=32), nullable=True),
    sa.Column('available_balance', sa.Numeric(precision=38, scale=18), server_default=sa.text('0'), nullable=False),
    sa.Column('locked_balance', sa.Numeric(precision=38, scale=18), server_default=sa.text('0'), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("((owner_type = 'user' AND user_id IS NOT NULL AND system_account IS NULL) OR (owner_type = 'system' AND user_id IS NULL AND system_account IS NOT NULL))", name=op.f('ck_wallets_valid_owner')),
    sa.CheckConstraint('available_balance >= 0', name=op.f('ck_wallets_available_balance_non_negative')),
    sa.CheckConstraint('locked_balance >= 0', name=op.f('ck_wallets_locked_balance_non_negative')),
    sa.ForeignKeyConstraint(['asset_id'], ['assets.id'], name=op.f('fk_wallets_asset_id_assets'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_wallets_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_wallets')),
    sa.UniqueConstraint('system_account', 'asset_id', name='system_account_asset'),
    sa.UniqueConstraint('user_id', 'asset_id', name='user_asset')
    )
    op.create_index(op.f('ix_wallets_asset_id'), 'wallets', ['asset_id'], unique=False)
    op.create_index(op.f('ix_wallets_user_id'), 'wallets', ['user_id'], unique=False)
    op.create_table('ledger_entries',
    sa.Column('transaction_id', sa.UUID(), nullable=False),
    sa.Column('wallet_id', sa.UUID(), nullable=False),
    sa.Column('entry_type', sa.Enum('debit', 'credit', name='ledger_entry_type'), nullable=False),
    sa.Column('balance_bucket', sa.Enum('available', 'locked', name='balance_bucket'), nullable=False),
    sa.Column('amount', sa.Numeric(precision=38, scale=18), nullable=False),
    sa.Column('sequence', sa.Integer(), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('amount > 0', name=op.f('ck_ledger_entries_amount_positive')),
    sa.ForeignKeyConstraint(['transaction_id'], ['ledger_transactions.id'], name=op.f('fk_ledger_entries_transaction_id_ledger_transactions'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['wallet_id'], ['wallets.id'], name=op.f('fk_ledger_entries_wallet_id_wallets'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_ledger_entries')),
    sa.UniqueConstraint('transaction_id', 'sequence', name='transaction_sequence')
    )
    op.create_index(op.f('ix_ledger_entries_transaction_id'), 'ledger_entries', ['transaction_id'], unique=False)
    op.create_index(op.f('ix_ledger_entries_wallet_id'), 'ledger_entries', ['wallet_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_ledger_entries_wallet_id'), table_name='ledger_entries')
    op.drop_index(op.f('ix_ledger_entries_transaction_id'), table_name='ledger_entries')
    op.drop_table('ledger_entries')
    op.drop_index(op.f('ix_wallets_user_id'), table_name='wallets')
    op.drop_index(op.f('ix_wallets_asset_id'), table_name='wallets')
    op.drop_table('wallets')
    op.drop_index(op.f('ix_ledger_transactions_reference'), table_name='ledger_transactions')
    op.drop_table('ledger_transactions')
    op.drop_index(op.f('ix_assets_code'), table_name='assets')
    op.drop_table('assets')
    # ### end Alembic commands ###

    op.execute("DROP TYPE IF EXISTS balance_bucket")
    op.execute("DROP TYPE IF EXISTS ledger_entry_type")
    op.execute("DROP TYPE IF EXISTS wallet_owner_type")
    op.execute("DROP TYPE IF EXISTS ledger_transaction_status")
    op.execute("DROP TYPE IF EXISTS ledger_transaction_type")
